# url ou dominio
@URL = http://localhost
# Porta do servidor
@PORT = 3600
# endpoint ou rota do teste
@ENDPOINT = eventos
# uri - rota final do teste
 @URI = {{URL}}:{{PORT}}/{{ENDPOINT}}

GET {{URI}}
###
GET {{URI}}/5

###
POST {{URI}}
Content-Type: application/json; charset=utf-8

  {
      "titulo": "Festival de Jazz na Praça",
      "data": "2026-06-22 23:00:00",
      "local" : "Praça central",
      "descricao": "Um evento cultural incrível com os melhores músicos da região. Entrada gratuita para todos!",
      "foto": "1.png"

      
    }

###
PUT {{URI}}/2
Content-Type: application/json; charset=utf-8

  {
      
      "titulo": "Noite do Rock no Bar do Zé",
      "data": "2026-06-23 05:00:00",
      "local": "Bar do seu zé",
      "descricao": "As melhores bandas de rock clássico a noite toda. Chopp gelado e muita diversão!",
      "foto": "2.png"
    }


###
DELETE {{URI}}/3