# url ou dominio
@URL = http://localhost
# Porta do servidor
@PORT = 3600
# endpoint ou rota do teste
@ENDPOINT = locais
# uri - rota final do teste
@URI = {{URL}}:{{PORT}}/{{ENDPOINT}}

GET {{URI}}
###
GET {{URI}}/5

###
POST {{URI}}
Content-Type: application/json; charset=utf-8

  {
      "name": "lulu",
      "email": "lulu@gmail.com.",
      "password": "abc123"
    }

###
PUT {{URI}}/2
Content-Type: application/json; charset=utf-8

  {
       "name": "felipe",
      "email": "fefe@gmail.com.",
      "password": "123abc"
    
  }


###
DELETE {{URI}}/1