@host = http://localhost
@port = 3600
@endpoint = upload

@url = {{host}}:{{port}}/{{endpoint}} 


###
# inclui novos registros
POST  {{url}}
Content-Type: multipart/form-data; boundary=MinhaBoundary

--MinhaBoundary
Content-Disposition: form-data; name="title"

Teste upload
--MinhaBoundary
Content-Disposition: form-data; name="avatar"; filename="22.png"
Content-Type: image/png

< ./22.png
--MinhaBoundary--

